name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lilja
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          ls -al
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build . --file Dockerfile -t lilja/syex:latest -t lilja/syex:$VERSION;
      - name: Push image to docker hub
        run: docker push lilja/syex
